# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20171005_2305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='candidate',
            new_name='student',
        ),
    ]
