# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20171009_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_name', models.CharField(max_length=10)),
                ('fortnightly_meeting', models.TextField()),
                ('party_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Student')),
            ],
        ),
    ]
