# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='student',
        ),
        migrations.AlterField(
            model_name='team',
            name='party_number',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
