# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_delete_uploadfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_name',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
