# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_assignment_assignment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_name',
            field=models.TextField(),
        ),
    ]
