# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_project_supervisor_tutor_unit_coordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='area',
        ),
    ]
