# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_remove_student_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
