# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_document_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document_Project',
        ),
    ]
