# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_delete_document_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='cdate',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='article',
            name='document',
            field=models.FileField(default=0, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
