# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('student_number', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
