# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20171005_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='party_number',
        ),
        migrations.AddField(
            model_name='poll',
            name='area',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
