# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Detail',
            new_name='information',
        ),
    ]
